language: python
python:
- '3.6'
install:
- pip install .
- pip install codecov
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  username: magdan
  password:
    secure: SPIysdWMUgSXzp8sLhcjj0HAMsRqLKTsv6P7p7l5M6LqT7AhTmDQWvY+44qcom8hjE2aglPu73uU14K1NqekJ2t0Rf+bSBd0XaJlDb0SuRhAkhJqIxhxn/0cqDqlMvXdw0GyaJq1IksmNWUsKeZq+esyOor5XUB3kPeX6gGzWiOsdcLCq1TvJA6/uZ8aRzOSUY9uFWymS9KxozrRaijqo1NDy3Swf20+TAUPbspJGqrgbIihYSBsBj8MBkxZfF6VoCHieI0pOIuZHCFtEdhGELl2uewRxys16EEGxcIHZeAXgGjRUUQXgFUbmIWwLP6t19WF68b6Lc7OHliieLaLQyJ07XOqeIeJmGhl/TyM1JgCTqgGUFcc+5TCbAt0DPPWCgg6zc6wbh1L+WwD8WUMj6wzBAnSuZFgCfzpXs+rROZBYdHDY89qwrwmJgWsiEPYxcyoyoRb2kaumGp4hwMysotd3khSIi+jU591t2KA7b30xbE1cB7+JgC3jHEAY1UNgt1PdPOtmHUAN7oKcRKdw5LRo22nU5qdxLUXP4SbhgcLRNjBYTH4okJ1sAxoTqY278ayCeiQ5hXWiQNtt3DkOPYNJbVJIPpLesOuCP5xHVO4vZkx6tXb2gG5EThqeYMl8UKCnSBNT2MqQ4a6FCJz0E1Qa+KKjPSrwu81U7dzaFU=
  on:
    tags: true
